services:
  caddy:
    container_name: caddy
    image: caddy
    ports:
    - "80:80"
    - "443:443"
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./frontend/Caddyfile:/etc/caddy/Caddyfile
      - ./frontend/dist:/usr/share/caddy
    depends_on:
      - backend

  backend:
    build: ./backend
    env_file: 
      - ./backend/.env
    ports:
      - 3000:3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

volumes:
  caddy-config:
  caddy-data:
  mongodata:
